name: Renovate Validate

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
      - name: yarn install and test
        run: |
          yarn --frozen-lockfile
          yarn test
        env:
          HUSKY: 0
